version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      prettier:
        patterns:
          - "prettier"
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
